/**
 * SmritiNER - Game 8: Odd One Out (Omilto Basoni)
 * Culturally Grounded Semantic Taxonomy for North-Eastern Indian & Universal Domains
 * Supporting Multi-Lingual Localizations: Assamese, Bengali, Hindi, English.
 * All Subcategories configured with >= 6-8 authentic items for rigorous Tier 1-9 testing.
 */

import type { CategoryItem } from './types';
import type { SupportedLanguage } from '../../types/prescription';

export interface CategoryMetadata {
  id: string;
  name: Record<SupportedLanguage, string>;
  domain: string; // 'cultural_northeast', 'nature_fauna', 'everyday_life', 'tools_crafts', 'transport'
}

export const CATEGORIES_METADATA: Record<string, CategoryMetadata> = {
  bihu_instruments: {
    id: 'bihu_instruments',
    domain: 'cultural_northeast',
    name: {
      as: 'বিহু আৰু পৰম্পৰাগত বাদ্যযন্ত্ৰ',
      bn: 'বিহু ও ঐতিহ্যবাহী বাদ্যযন্ত্র',
      hi: 'बिहू और पारंपरिक वाद्ययंत्र',
      en: 'Bihu & Folk Musical Instruments',
    },
  },
  modern_instruments: {
    id: 'modern_instruments',
    domain: 'everyday_life',
    name: {
      as: 'আধুনিক বাদ্যযন্ত্ৰ',
      bn: 'আধুনিক বাদ্যযন্ত্র',
      hi: 'आधुनिक वाद्ययंत्र',
      en: 'Modern Musical Instruments',
    },
  },
  ne_textiles: {
    id: 'ne_textiles',
    domain: 'cultural_northeast',
    name: {
      as: 'উত্তৰ-পূবৰ পৰম্পৰাগত বস্ত্ৰ',
      bn: 'উত্তর-পূর্বের ঐতিহ্যবাহী বস্ত্র',
      hi: 'उत्तर-पूर्व के पारंपरिक वस्त्र',
      en: 'Traditional North-East Handlooms',
    },
  },
  modern_clothing: {
    id: 'modern_clothing',
    domain: 'everyday_life',
    name: {
      as: 'আধুনিক সাজ-পোছাক',
      bn: 'আধুনিক পোশাক',
      hi: 'आधुनिक वस्त्र',
      en: 'Modern Western Apparel',
    },
  },
  ne_wildlife: {
    id: 'ne_wildlife',
    domain: 'nature_fauna',
    name: {
      as: 'উত্তৰ-পূবৰ বিশেষ বন্যপ্ৰাণী',
      bn: 'উত্তর-পূর্বের বিশেষ বন্যপ্রাণী',
      hi: 'उत्तर-पूर्व के विशेष वन्यजीव',
      en: 'North-East Native Wildlife',
    },
  },
  farm_animals: {
    id: 'farm_animals',
    domain: 'nature_fauna',
    name: {
      as: 'ঘৰচীয়া পোহনীয়া জীৱ-জন্তু',
      bn: 'গৃহপালিত পশুপাখি',
      hi: 'घरेलू पालतू पशु',
      en: 'Domestic Farm Animals',
    },
  },
  wild_predators: {
    id: 'wild_predators',
    domain: 'nature_fauna',
    name: {
      as: 'বন্য মাংসভোজী চিকাৰী প্ৰাণী',
      bn: 'বন্য মাংসাশী শিকারী প্রাণী',
      hi: 'जंगली शिकारी मांसाहारी जानवर',
      en: 'Wild Apex Predators',
    },
  },
  ne_crafts: {
    id: 'ne_crafts',
    domain: 'cultural_northeast',
    name: {
      as: 'অসম আৰু উত্তৰ-পূবৰ লোকশিল্প আৰু বাচন',
      bn: 'আসাম ও উত্তর-পূর্বের লোকশিল্প ও বাসন',
      hi: 'असम और पूर्वोत्तर के लोकशिल्प और बर्तन',
      en: 'North-East Heritage Crafts & Utensils',
    },
  },
  industrial_tools: {
    id: 'industrial_tools',
    domain: 'tools_crafts',
    name: {
      as: 'যান্ত্ৰিক আৰু নিৰ্মাণ সঁজুলি',
      bn: 'যান্ত্রিক ও নির্মাণ সরঞ্জাম',
      hi: 'यांत्रिक एवं निर्माण उपकरण',
      en: 'Hardware & Construction Tools',
    },
  },
  ne_produce: {
    id: 'ne_produce',
    domain: 'cultural_northeast',
    name: {
      as: 'উত্তৰ-পূবৰ থলুৱা কৃষিজাত খাদ্য',
      bn: 'উত্তর-পূর্বের স্থানীয় কৃষিজাত খাদ্য',
      hi: 'पूर्वोत्तर की स्थानीय कृषि उपज',
      en: 'North-East Indigenous Agricultural Produce',
    },
  },
  sweet_fruits: {
    id: 'sweet_fruits',
    domain: 'everyday_life',
    name: {
      as: 'মিঠা ফল-মূল',
      bn: 'মিষ্টি ফলমূল',
      hi: 'मीठे फल',
      en: 'Sweet Orchard Fruits',
    },
  },
  land_vehicles: {
    id: 'land_vehicles',
    domain: 'transport',
    name: {
      as: 'স্থলপথৰ যান-বাহন',
      bn: 'স্থলপথের যানবাহন',
      hi: 'सड़क परिवहन वाहन',
      en: 'Land Road Vehicles',
    },
  },
  water_air_vehicles: {
    id: 'water_air_vehicles',
    domain: 'transport',
    name: {
      as: 'জলপথ আৰু আকাশী যান',
      bn: 'জলপথ ও আকাশযান',
      hi: 'जल एवं वायु परिवहन वाहन',
      en: 'Water & Aviation Vessels',
    },
  },
  rainy_weather: {
    id: 'rainy_weather',
    domain: 'everyday_life',
    name: {
      as: 'বৰষুণ আৰু ধুমুহাৰ বতৰ',
      bn: 'বৃষ্টি ও ঝড়ের আবহাওয়া',
      hi: 'वर्षा और तूफान का मौसम',
      en: 'Monsoon & Rainy Weather',
    },
  },
  sunny_weather: {
    id: 'sunny_weather',
    domain: 'everyday_life',
    name: {
      as: 'ৰ\'দঘাই ফৰকাল বতৰ',
      bn: 'রোদ ঝলমলে পরিষ্কার আবহাওয়া',
      hi: 'धूपदार साफ मौसम',
      en: 'Bright Sunny Weather',
    },
  },
};

export const CATEGORY_ITEMS: CategoryItem[] = [
  // ─── 1. Bihu & North-East Folk Musical Instruments (8 Items) ──────────────
  {
    id: 'bihu_dhol',
    symbol: '🥁',
    name: { as: 'ঢোল', bn: 'ঢোল', hi: 'ढोल', en: 'Bihu Dhol' },
    category: 'instruments',
    subcategory: 'bihu_instruments',
    attributes: ['music', 'northeast', 'traditional', 'percussion', 'bihu', 'handcrafted'],
  },
  {
    id: 'bihu_pepa',
    symbol: '🎺',
    name: { as: 'পেঁপা', bn: 'পেঁপা', hi: 'पेपा (सींग वाद्य)', en: 'Buffalo Horn Pepa' },
    category: 'instruments',
    subcategory: 'bihu_instruments',
    attributes: ['music', 'northeast', 'traditional', 'wind', 'bihu', 'handcrafted'],
  },
  {
    id: 'bihu_gogona',
    symbol: '🪕',
    name: { as: 'গগনা', bn: 'গগনা', hi: 'गोगोना (बांस वाद्य)', en: 'Bamboo Gogona' },
    category: 'instruments',
    subcategory: 'bihu_instruments',
    attributes: ['music', 'northeast', 'traditional', 'plucked', 'bihu', 'bamboo'],
  },
  {
    id: 'bihu_toka',
    symbol: '🥢',
    name: { as: 'টকা', bn: 'টকা', hi: 'टोका (बांस क्लैपर)', en: 'Bamboo Toka' },
    category: 'instruments',
    subcategory: 'bihu_instruments',
    attributes: ['music', 'northeast', 'traditional', 'percussion', 'bihu', 'bamboo'],
  },
  {
    id: 'bihu_baahi',
    symbol: '🪈',
    name: { as: 'বাঁহী', bn: 'বাঁশি', hi: 'बांसुरी', en: 'Bamboo Flute' },
    category: 'instruments',
    subcategory: 'bihu_instruments',
    attributes: ['music', 'northeast', 'traditional', 'wind', 'bamboo'],
  },
  {
    id: 'bihu_taal',
    symbol: '🔔',
    name: { as: 'তাল (কাঁহৰ)', bn: 'কাঁসির তাল', hi: 'कांस्य मंजीरा (ताल)', en: 'Bell-metal Taal' },
    category: 'instruments',
    subcategory: 'bihu_instruments',
    attributes: ['music', 'northeast', 'traditional', 'percussion', 'bell_metal'],
  },
  {
    id: 'bihu_xutuli',
    symbol: '🪈',
    name: { as: 'সুতুলি', bn: 'সুতুলি (মাটির বাঁশি)', hi: 'सुतुली (मिट्टी की सीटी)', en: 'Clay Xutuli' },
    category: 'instruments',
    subcategory: 'bihu_instruments',
    attributes: ['music', 'northeast', 'traditional', 'wind', 'bihu', 'clay'],
  },
  {
    id: 'bihu_khol',
    symbol: '🪘',
    name: { as: 'খোল (সত্ৰীয়া)', bn: 'খোল (সত্রীয়া)', hi: 'खोल (सत्रीय मृदंग)', en: 'Sattriya Khol' },
    category: 'instruments',
    subcategory: 'bihu_instruments',
    attributes: ['music', 'northeast', 'traditional', 'percussion', 'handcrafted'],
  },

  // ─── 2. Modern Western Musical Instruments (7 Items) ───────────────────────
  {
    id: 'mod_guitar',
    symbol: '🎸',
    name: { as: 'ইলেক্ট্ৰিক গীটাৰ', bn: 'গিটার', hi: 'गिटार', en: 'Electric Guitar' },
    category: 'instruments',
    subcategory: 'modern_instruments',
    attributes: ['music', 'modern', 'string', 'electric'],
  },
  {
    id: 'mod_piano',
    symbol: '🎹',
    name: { as: 'পিয়ানো কিবৰ্ড', bn: 'পিয়ানো', hi: 'पियानो', en: 'Grand Piano' },
    category: 'instruments',
    subcategory: 'modern_instruments',
    attributes: ['music', 'modern', 'keyboard', 'acoustic'],
  },
  {
    id: 'mod_saxophone',
    symbol: '🎷',
    name: { as: 'চেক্স\'ফন', bn: 'স্যাক্সোফোন', hi: 'सैक्सोफोन', en: 'Saxophone' },
    category: 'instruments',
    subcategory: 'modern_instruments',
    attributes: ['music', 'modern', 'wind', 'brass'],
  },
  {
    id: 'mod_violin',
    symbol: '🎻',
    name: { as: 'বায়লিন', bn: 'বেহালা', hi: 'वायलिन', en: 'Violin' },
    category: 'instruments',
    subcategory: 'modern_instruments',
    attributes: ['music', 'modern', 'string', 'acoustic'],
  },
  {
    id: 'mod_drums',
    symbol: '🥁',
    name: { as: 'ড্ৰাম কিট', bn: 'ড্রাম কিট', hi: 'ड्रम किट', en: 'Rock Drum Kit' },
    category: 'instruments',
    subcategory: 'modern_instruments',
    attributes: ['music', 'modern', 'percussion'],
  },
  {
    id: 'mod_trumpet',
    symbol: '🎺',
    name: { as: 'ট্ৰাম্পেট', bn: 'ট্রাম্পেট', hi: 'तुरही (ट्रम्पेट)', en: 'Brass Trumpet' },
    category: 'instruments',
    subcategory: 'modern_instruments',
    attributes: ['music', 'modern', 'wind', 'brass'],
  },
  {
    id: 'mod_accordion',
    symbol: '🪗',
    name: { as: 'একৰ্ডিয়ান', bn: 'অ্যাকর্ডিয়ান', hi: 'अकॉर्डियन', en: 'Accordion' },
    category: 'instruments',
    subcategory: 'modern_instruments',
    attributes: ['music', 'modern', 'wind', 'keyboard'],
  },

  // ─── 3. Traditional North-East Handlooms & Textiles (8 Items) ──────────────
  {
    id: 'tex_gamosa',
    symbol: '🧣',
    name: { as: 'গামোচা', bn: 'গামছা (অসমীয়া)', hi: 'गमोसा (असमिया पटका)', en: 'Assamese Gamosa' },
    category: 'clothing',
    subcategory: 'ne_textiles',
    attributes: ['clothing', 'northeast', 'traditional', 'cotton', 'handloom', 'red_white'],
  },
  {
    id: 'tex_mekhela',
    symbol: '🥻',
    name: { as: 'মেখেলা চাদৰ', bn: 'মেখেলা চাদর', hi: 'मेखेला चादोर', en: 'Mekhela Chador' },
    category: 'clothing',
    subcategory: 'ne_textiles',
    attributes: ['clothing', 'northeast', 'traditional', 'silk', 'handloom', 'formal'],
  },
  {
    id: 'tex_eri_shawl',
    symbol: '🧣',
    name: { as: 'এৰী চাদৰ', bn: 'এরি রেশম শাল', hi: 'एरी रेशम शॉल', en: 'Eri Peace-Silk Shawl' },
    category: 'clothing',
    subcategory: 'ne_textiles',
    attributes: ['clothing', 'northeast', 'traditional', 'silk', 'warm', 'handloom'],
  },
  {
    id: 'tex_dokhona',
    symbol: '👗',
    name: { as: 'দখনা (বড়ো)', bn: 'দখনা (বোড়ো পোশাক)', hi: 'दोखोना (बोडो परिधान)', en: 'Bodo Dokhona' },
    category: 'clothing',
    subcategory: 'ne_textiles',
    attributes: ['clothing', 'northeast', 'traditional', 'cotton', 'handloom'],
  },
  {
    id: 'tex_phanek',
    symbol: '👗',
    name: { as: 'ফানেক (মণিপুৰী)', bn: 'ফানেক (মণিপুরী পোশাক)', hi: 'फानेक (मणिपुरी परिधान)', en: 'Manipuri Phanek' },
    category: 'clothing',
    subcategory: 'ne_textiles',
    attributes: ['clothing', 'northeast', 'traditional', 'handloom'],
  },
  {
    id: 'tex_muga_silk',
    symbol: '🥻',
    name: { as: 'মুগা ৰেচম শাড়ী', bn: 'মুগা সিল্ক শাড়ি', hi: 'मूंगा रेशम साड़ी', en: 'Golden Muga Silk' },
    category: 'clothing',
    subcategory: 'ne_textiles',
    attributes: ['clothing', 'northeast', 'traditional', 'silk', 'handloom', 'golden'],
  },
  {
    id: 'tex_rignai',
    symbol: '👗',
    name: { as: 'ৰিগনাই (ত্ৰিপুৰী)', bn: 'রিগনাই (ত্রিপুরী)', hi: 'रिगनाई (त्रिपुरी परिधान)', en: 'Tripuri Rignai' },
    category: 'clothing',
    subcategory: 'ne_textiles',
    attributes: ['clothing', 'northeast', 'traditional', 'handloom'],
  },
  {
    id: 'tex_naga_shawl',
    symbol: '🧣',
    name: { as: 'নাগা চাদৰ', bn: 'নাগা শাল', hi: 'नागा शॉल', en: 'Traditional Naga Shawl' },
    category: 'clothing',
    subcategory: 'ne_textiles',
    attributes: ['clothing', 'northeast', 'traditional', 'handloom', 'warm'],
  },

  // ─── 4. Modern Western Clothing (8 Items) ──────────────────────────────────
  {
    id: 'clo_jeans',
    symbol: '👖',
    name: { as: 'ডেনিম জিন্স', bn: 'জিন্স প্যান্ট', hi: 'डेनिम जींस', en: 'Denim Jeans' },
    category: 'clothing',
    subcategory: 'modern_clothing',
    attributes: ['clothing', 'modern', 'casual', 'denim'],
  },
  {
    id: 'clo_tshirt',
    symbol: '👕',
    name: { as: 'টি-ছাৰ্ট', bn: 'টি-শার্ট', hi: 'टी-शर्ट', en: 'Casual T-Shirt' },
    category: 'clothing',
    subcategory: 'modern_clothing',
    attributes: ['clothing', 'modern', 'casual', 'cotton'],
  },
  {
    id: 'clo_suit',
    symbol: '🧥',
    name: { as: 'কোট / ব্লেজাৰ', bn: 'কোট / ব্লেজার', hi: 'कोट / ब्लेज़र', en: 'Formal Suit Coat' },
    category: 'clothing',
    subcategory: 'modern_clothing',
    attributes: ['clothing', 'modern', 'formal', 'outerwear'],
  },
  {
    id: 'clo_swimsuit',
    symbol: '🩱',
    name: { as: 'সাঁতোৰা সাজ', bn: 'সাঁতারের পোশাক', hi: 'तैराकी की पोशाक', en: 'Swimsuit' },
    category: 'clothing',
    subcategory: 'modern_clothing',
    attributes: ['clothing', 'modern', 'sport', 'summer'],
  },
  {
    id: 'clo_hoodie',
    symbol: '🧥',
    name: { as: 'হুডী জেকেট', bn: 'হুডি জ্যাকেট', hi: 'हूडी जैकेट', en: 'Winter Hoodie' },
    category: 'clothing',
    subcategory: 'modern_clothing',
    attributes: ['clothing', 'modern', 'casual', 'warm'],
  },
  {
    id: 'clo_socks',
    symbol: '🧦',
    name: { as: 'মোজা', bn: 'মোজা', hi: 'मोज़े', en: 'Cotton Socks' },
    category: 'clothing',
    subcategory: 'modern_clothing',
    attributes: ['clothing', 'modern', 'casual'],
  },
  {
    id: 'clo_hat',
    symbol: '🧢',
    name: { as: 'বেছবল কেপ', bn: 'ক্যাপ টুপি', hi: 'बेसबॉल कैप', en: 'Baseball Cap' },
    category: 'clothing',
    subcategory: 'modern_clothing',
    attributes: ['clothing', 'modern', 'casual'],
  },
  {
    id: 'clo_gloves',
    symbol: '🧤',
    name: { as: 'হাতমোজা', bn: 'দস্তানা', hi: 'दस्ताने', en: 'Leather Gloves' },
    category: 'clothing',
    subcategory: 'modern_clothing',
    attributes: ['clothing', 'modern', 'warm'],
  },

  // ─── 5. North-East Native Wildlife (8 Items) ───────────────────────────────
  {
    id: 'wild_rhino',
    symbol: '🦏',
    name: { as: 'এশিঙীয়া গঁড়', bn: 'একশৃঙ্গ গণ্ডার', hi: 'एक सींग वाला गैंडा', en: 'One-horned Rhino' },
    category: 'animals',
    subcategory: 'ne_wildlife',
    attributes: ['animals', 'northeast', 'wild', 'herbivore', 'protected', 'mammal'],
  },
  {
    id: 'wild_hoolock',
    symbol: '🐵',
    name: { as: 'হলৌ বান্দৰ', bn: 'উল্লুক (হুলক গিবন)', hi: 'हूलॉक गिब्बन', en: 'Hoolock Gibbon' },
    category: 'animals',
    subcategory: 'ne_wildlife',
    attributes: ['animals', 'northeast', 'wild', 'herbivore', 'tree_dwelling', 'mammal'],
  },
  {
    id: 'wild_sangai',
    symbol: '🦌',
    name: { as: 'চাংগাই হৰিণা', bn: 'সাংগাই হরিণ', hi: 'संगाई हिरण (मणिपुर)', en: 'Sangai Brow-antlered Deer' },
    category: 'animals',
    subcategory: 'ne_wildlife',
    attributes: ['animals', 'northeast', 'wild', 'herbivore', 'protected', 'mammal'],
  },
  {
    id: 'wild_hornbill',
    symbol: '🦜',
    name: { as: 'ধনেশ পক্ষী', bn: 'ধনেশ পাখি (হর্নবিল)', hi: 'धनेश पक्षी (हॉर्नबिल)', en: 'Great Indian Hornbill' },
    category: 'animals',
    subcategory: 'ne_wildlife',
    attributes: ['animals', 'northeast', 'wild', 'flying', 'bird'],
  },
  {
    id: 'wild_dolphin',
    symbol: '🐬',
    name: { as: 'শিশু (ব্ৰহ্মপুত্ৰৰ শিহু)', bn: 'গাঙ্গেয় শুশুক', hi: 'गंगा/ब्रह्मपुत्र डॉल्फिन (सिहू)', en: 'Gangetic River Dolphin' },
    category: 'animals',
    subcategory: 'ne_wildlife',
    attributes: ['animals', 'northeast', 'wild', 'aquatic', 'protected', 'mammal'],
  },
  {
    id: 'wild_golden_langur',
    symbol: '🐒',
    name: { as: 'সোণালী বান্দৰ', bn: 'সোনালী ল্যাঙ্গুর', hi: 'सुनहरा लंगूर', en: 'Gee\'s Golden Langur' },
    category: 'animals',
    subcategory: 'ne_wildlife',
    attributes: ['animals', 'northeast', 'wild', 'herbivore', 'protected', 'mammal'],
  },
  {
    id: 'wild_pygmy_hog',
    symbol: '🐗',
    name: { as: 'নল গাহৰি', bn: 'পিগমি হগ (বামন শূকর)', hi: 'पिग्मी हॉग (छोटा सूअर)', en: 'Pygmy Hog' },
    category: 'animals',
    subcategory: 'ne_wildlife',
    attributes: ['animals', 'northeast', 'wild', 'herbivore', 'protected', 'mammal'],
  },
  {
    id: 'wild_clouded_leopard',
    symbol: '🐆',
    name: { as: 'মেঘালী নাহৰফুটুকী', bn: 'ক্লাউডেড লেপার্ড', hi: 'धूमिल तेंदुआ', en: 'Clouded Leopard' },
    category: 'animals',
    subcategory: 'ne_wildlife',
    attributes: ['animals', 'northeast', 'wild', 'carnivore', 'protected', 'mammal'],
  },

  // ─── 6. Domestic Farm Animals (8 Items) ────────────────────────────────────
  {
    id: 'farm_cow',
    symbol: '🐮',
    name: { as: 'গৰু', bn: 'গরু', hi: 'गाय', en: 'Dairy Cow' },
    category: 'animals',
    subcategory: 'farm_animals',
    attributes: ['animals', 'domestic', 'herbivore', 'mammal', 'dairy'],
  },
  {
    id: 'farm_goat',
    symbol: '🐐',
    name: { as: 'ছাগলী', bn: 'ছাগল', hi: 'बकरी', en: 'Farm Goat' },
    category: 'animals',
    subcategory: 'farm_animals',
    attributes: ['animals', 'domestic', 'herbivore', 'mammal'],
  },
  {
    id: 'farm_pig',
    symbol: '🐷',
    name: { as: 'গাহৰি', bn: 'শূকর', hi: 'सूअर', en: 'Domestic Pig' },
    category: 'animals',
    subcategory: 'farm_animals',
    attributes: ['animals', 'domestic', 'omnivore', 'mammal'],
  },
  {
    id: 'farm_chicken',
    symbol: '🐔',
    name: { as: 'কুকুৰা', bn: 'মুরগি', hi: 'मुर्गी', en: 'Farm Chicken' },
    category: 'animals',
    subcategory: 'farm_animals',
    attributes: ['animals', 'domestic', 'bird', 'egg_laying'],
  },
  {
    id: 'farm_duck',
    symbol: '🦆',
    name: { as: 'হাঁহ', bn: 'হাঁস', hi: 'बतख', en: 'Pond Duck' },
    category: 'animals',
    subcategory: 'farm_animals',
    attributes: ['animals', 'domestic', 'bird', 'aquatic'],
  },
  {
    id: 'farm_horse',
    symbol: '🐴',
    name: { as: 'ঘোঁৰা', bn: 'ঘোড়া', hi: 'घोड़ा', en: 'Domestic Horse' },
    category: 'animals',
    subcategory: 'farm_animals',
    attributes: ['animals', 'domestic', 'herbivore', 'mammal'],
  },
  {
    id: 'farm_sheep',
    symbol: '🐑',
    name: { as: 'ভেড়া', bn: 'ভেড়া', hi: 'भेड़', en: 'Wool Sheep' },
    category: 'animals',
    subcategory: 'farm_animals',
    attributes: ['animals', 'domestic', 'herbivore', 'mammal'],
  },
  {
    id: 'farm_rabbit',
    symbol: '🐰',
    name: { as: 'শহা পহু', bn: 'খরগোশ', hi: 'खरगोश', en: 'Pet Rabbit' },
    category: 'animals',
    subcategory: 'farm_animals',
    attributes: ['animals', 'domestic', 'herbivore', 'mammal'],
  },

  // ─── 7. Wild Apex Predators (7 Items) ──────────────────────────────────────
  {
    id: 'pred_tiger',
    symbol: '🐯',
    name: { as: 'ঢেঁকীয়াপতীয়া বাঘ', bn: 'রয়েল বেঙ্গল টাইগার', hi: 'बंगाल टाइगर', en: 'Royal Bengal Tiger' },
    category: 'animals',
    subcategory: 'wild_predators',
    attributes: ['animals', 'wild', 'carnivore', 'predator', 'mammal'],
  },
  {
    id: 'pred_lion',
    symbol: '🦁',
    name: { as: 'সিংহ', bn: 'সিংহ', hi: 'शेर', en: 'Wild Lion' },
    category: 'animals',
    subcategory: 'wild_predators',
    attributes: ['animals', 'wild', 'carnivore', 'predator', 'mammal'],
  },
  {
    id: 'pred_leopard',
    symbol: '🐆',
    name: { as: 'নাহৰফুটুকী বাঘ', bn: 'চিতাবাঘ', hi: 'तेंदुआ', en: 'Spotted Leopard' },
    category: 'animals',
    subcategory: 'wild_predators',
    attributes: ['animals', 'wild', 'carnivore', 'predator', 'mammal'],
  },
  {
    id: 'pred_bear',
    symbol: '🐻',
    name: { as: 'ভালুক', bn: 'ভাল্লুক', hi: 'भालू', en: 'Himalayan Bear' },
    category: 'animals',
    subcategory: 'wild_predators',
    attributes: ['animals', 'wild', 'omnivore', 'predator', 'mammal'],
  },
  {
    id: 'pred_wolf',
    symbol: '🐺',
    name: { as: 'কুকুৰনেচীয়া বাঘ', bn: 'নেকড়ে বাঘ', hi: 'भेड़िया', en: 'Wild Wolf' },
    category: 'animals',
    subcategory: 'wild_predators',
    attributes: ['animals', 'wild', 'carnivore', 'predator', 'mammal'],
  },
  {
    id: 'pred_cheetah',
    symbol: '🐆',
    name: { as: 'চিতা বাঘ', bn: 'চিতা', hi: 'चीता', en: 'Wild Cheetah' },
    category: 'animals',
    subcategory: 'wild_predators',
    attributes: ['animals', 'wild', 'carnivore', 'predator', 'mammal'],
  },
  {
    id: 'pred_fox',
    symbol: '🦊',
    name: { as: 'শিয়াল', bn: 'শিয়াল', hi: 'लोमड़ी', en: 'Wild Fox' },
    category: 'animals',
    subcategory: 'wild_predators',
    attributes: ['animals', 'wild', 'carnivore', 'predator', 'mammal'],
  },

  // ─── 8. North-East Heritage Crafts & Utensils (8 Items) ────────────────────
  {
    id: 'cft_xorai',
    symbol: '🏆',
    name: { as: 'কাঁহৰ শৰাই', bn: 'কাঁসার সরাই', hi: 'कांस्य सराई', en: 'Bell-metal Xorai' },
    category: 'tools_crafts',
    subcategory: 'ne_crafts',
    attributes: ['tools_crafts', 'northeast', 'traditional', 'bell_metal', 'ceremonial'],
  },
  {
    id: 'cft_japi',
    symbol: '👒',
    name: { as: 'অসমীয়া জাপি', bn: 'জাপি (ঐতিহ্যবাহী টুপি)', hi: 'जापी (पारंपरिक टोपी)', en: 'Assamese Jaapi' },
    category: 'tools_crafts',
    subcategory: 'ne_crafts',
    attributes: ['tools_crafts', 'northeast', 'traditional', 'bamboo', 'headwear'],
  },
  {
    id: 'cft_kula',
    symbol: '🧺',
    name: { as: 'বাঁহৰ কুলা', bn: 'বাঁশের কুলা', hi: 'सूप (कुला)', en: 'Bamboo Winnowing Kula' },
    category: 'tools_crafts',
    subcategory: 'ne_crafts',
    attributes: ['tools_crafts', 'northeast', 'traditional', 'bamboo', 'agricultural'],
  },
  {
    id: 'cft_kalah',
    symbol: '🏺',
    name: { as: 'কাঁহৰ কলহ', bn: 'কাঁসার কলস', hi: 'कांस्य कलश', en: 'Bell-metal Pitcher (Kalah)' },
    category: 'tools_crafts',
    subcategory: 'ne_crafts',
    attributes: ['tools_crafts', 'northeast', 'traditional', 'bell_metal', 'household'],
  },
  {
    id: 'cft_dala',
    symbol: '🧺',
    name: { as: 'বাঁহৰ ডালা', bn: 'বাঁশের ডালা', hi: 'बांस की डलिया (डाला)', en: 'Bamboo Dala Platter' },
    category: 'tools_crafts',
    subcategory: 'ne_crafts',
    attributes: ['tools_crafts', 'northeast', 'traditional', 'bamboo', 'household'],
  },
  {
    id: 'cft_baanbati',
    symbol: '🥣',
    name: { as: 'কাঁহৰ বাটি (বানবাটি)', bn: 'কাঁসার বানবাটি', hi: 'कांस्य कटोरी (बानबाटी)', en: 'Bell-metal Baanbati' },
    category: 'tools_crafts',
    subcategory: 'ne_crafts',
    attributes: ['tools_crafts', 'northeast', 'traditional', 'bell_metal', 'household'],
  },
  {
    id: 'cft_shitalpati',
    symbol: '🎋',
    name: { as: 'শীতল পাটি', bn: 'শীতল পাটি', hi: 'शीतल पाटी (चटाई)', en: 'Cool Cane Shitalpati' },
    category: 'tools_crafts',
    subcategory: 'ne_crafts',
    attributes: ['tools_crafts', 'northeast', 'traditional', 'cane', 'household'],
  },
  {
    id: 'cft_chalani',
    symbol: '🥢',
    name: { as: 'বাঁহৰ চালনী', bn: 'বাঁশের চালনি', hi: 'बांस की छलनी', en: 'Bamboo Chalani Sieve' },
    category: 'tools_crafts',
    subcategory: 'ne_crafts',
    attributes: ['tools_crafts', 'northeast', 'traditional', 'bamboo', 'household'],
  },

  // ─── 9. Hardware & Construction Tools (8 Items) ────────────────────────────
  {
    id: 'tool_hammer',
    symbol: '🔨',
    name: { as: 'হাতুৰী', bn: 'হাতুড়ি', hi: 'हथौड़ा', en: 'Steel Hammer' },
    category: 'tools_crafts',
    subcategory: 'industrial_tools',
    attributes: ['tools_crafts', 'modern', 'manual', 'metal', 'construction'],
  },
  {
    id: 'tool_wrench',
    symbol: '🔧',
    name: { as: 'ৰেঞ্চ / স্পেনাৰ', bn: 'রেঞ্চ', hi: 'रिंच (पाना)', en: 'Adjustable Wrench' },
    category: 'tools_crafts',
    subcategory: 'industrial_tools',
    attributes: ['tools_crafts', 'modern', 'manual', 'metal', 'repair'],
  },
  {
    id: 'tool_screwdriver',
    symbol: '🪛',
    name: { as: 'স্ক্রু-ড্ৰাইভাৰ', bn: 'স্ক্রু ড্রাইভার', hi: 'पेचकस', en: 'Screwdriver' },
    category: 'tools_crafts',
    subcategory: 'industrial_tools',
    attributes: ['tools_crafts', 'modern', 'manual', 'metal', 'repair'],
  },
  {
    id: 'tool_saw',
    symbol: '🪚',
    name: { as: 'কৰত', bn: 'করাত', hi: 'आरी (करौत)', en: 'Hand Saw' },
    category: 'tools_crafts',
    subcategory: 'industrial_tools',
    attributes: ['tools_crafts', 'modern', 'manual', 'metal', 'carpentry'],
  },
  {
    id: 'tool_pliers',
    symbol: '🗜️',
    name: { as: 'প্লেয়াৰ্চ (চেপেনা)', bn: 'প্লায়ার্স', hi: 'प्लायर्स (पिलास)', en: 'Grip Pliers' },
    category: 'tools_crafts',
    subcategory: 'industrial_tools',
    attributes: ['tools_crafts', 'modern', 'manual', 'metal', 'repair'],
  },
  {
    id: 'tool_drill',
    symbol: '🔩',
    name: { as: 'ইলেক্ট্ৰিক ড্ৰিল', bn: 'ড্রিল মেশিন', hi: 'ड्रिल मशीन', en: 'Power Drill' },
    category: 'tools_crafts',
    subcategory: 'industrial_tools',
    attributes: ['tools_crafts', 'modern', 'electric', 'metal', 'construction'],
  },
  {
    id: 'tool_axe',
    symbol: '🪓',
    name: { as: 'কুঠাৰ', bn: 'কুঠার', hi: 'कुल्हाड़ी', en: 'Steel Axe' },
    category: 'tools_crafts',
    subcategory: 'industrial_tools',
    attributes: ['tools_crafts', 'modern', 'manual', 'metal', 'cutting'],
  },
  {
    id: 'tool_tape',
    symbol: '📏',
    name: { as: 'জোখ লোৱা ফিতা', bn: 'পরিমাপ ফিতা', hi: 'मापने का फीता', en: 'Measuring Tape' },
    category: 'tools_crafts',
    subcategory: 'industrial_tools',
    attributes: ['tools_crafts', 'modern', 'manual', 'measuring'],
  },

  // ─── 10. North-East Agricultural Produce & Culinary (8 Items) ──────────────
  {
    id: 'prd_lemon',
    symbol: '🍋',
    name: { as: 'কাজী নেমু', bn: 'কাজী লেবু', hi: 'काजी नींबू', en: 'Assam Kaji Nemu' },
    category: 'fruits_food',
    subcategory: 'ne_produce',
    attributes: ['food', 'northeast', 'citrus', 'sour', 'organic'],
  },
  {
    id: 'prd_chilli',
    symbol: '🌶️',
    name: { as: 'ভোট জলকীয়া', bn: 'ভূত জলকিয়া (মরিচ)', hi: 'भूत जोलोकिया मिर्च', en: 'Bhut Jolokia (Ghost Pepper)' },
    category: 'fruits_food',
    subcategory: 'ne_produce',
    attributes: ['food', 'northeast', 'spicy', 'organic'],
  },
  {
    id: 'prd_tea',
    symbol: '🍃',
    name: { as: 'অসম চাহপাত', bn: 'আসাম চা পাতা', hi: 'असम चाय पत्ती', en: 'Assam Tea Leaves' },
    category: 'fruits_food',
    subcategory: 'ne_produce',
    attributes: ['food', 'northeast', 'beverage', 'aromatic'],
  },
  {
    id: 'prd_bamboo_shoot',
    symbol: '🎋',
    name: { as: 'বাঁহৰ গাজ', bn: 'বাঁশের কোঁড়ল', hi: 'बांस का अंकुर', en: 'Tender Bamboo Shoot' },
    category: 'fruits_food',
    subcategory: 'ne_produce',
    attributes: ['food', 'northeast', 'vegetable', 'traditional'],
  },
  {
    id: 'prd_joha_rice',
    symbol: '🌾',
    name: { as: 'জোহা চাউল', bn: 'জোহা চাল', hi: 'जोहा सुगंधित चावल', en: 'Aromatic Joha Rice' },
    category: 'fruits_food',
    subcategory: 'ne_produce',
    attributes: ['food', 'northeast', 'grain', 'aromatic'],
  },
  {
    id: 'prd_ou_tenga',
    symbol: '🍏',
    name: { as: 'ঔটেঙা', bn: 'চালতা (ঔটেঙা)', hi: 'हाथी सेब (ओउ तेंगा)', en: 'Elephant Apple (Ou Tenga)' },
    category: 'fruits_food',
    subcategory: 'ne_produce',
    attributes: ['food', 'northeast', 'sour', 'traditional'],
  },
  {
    id: 'prd_ginger',
    symbol: '🫚',
    name: { as: 'আদা', bn: 'আদা', hi: 'अदरक', en: 'Karbi Anglong Ginger' },
    category: 'fruits_food',
    subcategory: 'ne_produce',
    attributes: ['food', 'northeast', 'spice', 'organic'],
  },
  {
    id: 'prd_turmeric',
    symbol: '🌱',
    name: { as: 'লকাডং হালধি', bn: 'লাকাডং হলুদ', hi: 'लकाडोंग हल्दी (मेघालय)', en: 'Lakadong Turmeric' },
    category: 'fruits_food',
    subcategory: 'ne_produce',
    attributes: ['food', 'northeast', 'spice', 'organic'],
  },

  // ─── 11. Sweet Orchard Fruits (8 Items) ────────────────────────────────────
  {
    id: 'frt_apple',
    symbol: '🍎',
    name: { as: 'আপেল', bn: 'আপেল', hi: 'सेब', en: 'Red Apple' },
    category: 'fruits_food',
    subcategory: 'sweet_fruits',
    attributes: ['food', 'sweet', 'fruit', 'orchard'],
  },
  {
    id: 'frt_banana',
    symbol: '🍌',
    name: { as: 'কল', bn: 'কলা', hi: 'केला', en: 'Ripe Banana' },
    category: 'fruits_food',
    subcategory: 'sweet_fruits',
    attributes: ['food', 'sweet', 'fruit', 'tropical'],
  },
  {
    id: 'frt_mango',
    symbol: '🥭',
    name: { as: 'আম', bn: 'আম', hi: 'आम', en: 'Sweet Mango' },
    category: 'fruits_food',
    subcategory: 'sweet_fruits',
    attributes: ['food', 'sweet', 'fruit', 'tropical'],
  },
  {
    id: 'frt_grapes',
    symbol: '🍇',
    name: { as: 'আঙুৰ', bn: 'আঙুর', hi: 'अंगूर', en: 'Purple Grapes' },
    category: 'fruits_food',
    subcategory: 'sweet_fruits',
    attributes: ['food', 'sweet', 'fruit', 'vine'],
  },
  {
    id: 'frt_strawberry',
    symbol: '🍓',
    name: { as: 'ষ্ট্ৰবেৰী', bn: 'স্ট্রবেরি', hi: 'स्ट्रॉबेरी', en: 'Sweet Strawberry' },
    category: 'fruits_food',
    subcategory: 'sweet_fruits',
    attributes: ['food', 'sweet', 'fruit', 'berry'],
  },
  {
    id: 'frt_pineapple',
    symbol: '🍍',
    name: { as: 'আনাৰস', bn: 'আনারস', hi: 'अनानास', en: 'Tropical Pineapple' },
    category: 'fruits_food',
    subcategory: 'sweet_fruits',
    attributes: ['food', 'sweet', 'fruit', 'tropical'],
  },
  {
    id: 'frt_orange',
    symbol: '🍊',
    name: { as: 'কমলা', bn: 'কমলালেবু', hi: 'संतरा', en: 'Sweet Orange' },
    category: 'fruits_food',
    subcategory: 'sweet_fruits',
    attributes: ['food', 'sweet', 'fruit', 'citrus'],
  },
  {
    id: 'frt_papaya',
    symbol: '🍈',
    name: { as: 'অমিতা', bn: 'পেঁপে', hi: 'पपीता', en: 'Sweet Papaya' },
    category: 'fruits_food',
    subcategory: 'sweet_fruits',
    attributes: ['food', 'sweet', 'fruit', 'tropical'],
  },

  // ─── 12. Land Road Vehicles (7 Items) ──────────────────────────────────────
  {
    id: 'veh_car',
    symbol: '🚗',
    name: { as: 'মটৰ গাড়ী', bn: 'গাড়ি', hi: 'मोटर कार', en: 'Passenger Car' },
    category: 'vehicles',
    subcategory: 'land_vehicles',
    attributes: ['vehicles', 'land', 'motorized', 'wheels_4'],
  },
  {
    id: 'veh_bus',
    symbol: '🚌',
    name: { as: 'বাছ', bn: 'বাস', hi: 'बस', en: 'Public Bus' },
    category: 'vehicles',
    subcategory: 'land_vehicles',
    attributes: ['vehicles', 'land', 'motorized', 'public'],
  },
  {
    id: 'veh_auto',
    symbol: '🛺',
    name: { as: 'অট\' ৰিক্সা', bn: 'অটো রিকশা', hi: 'ऑटो रिक्शा', en: 'Auto Rickshaw' },
    category: 'vehicles',
    subcategory: 'land_vehicles',
    attributes: ['vehicles', 'land', 'motorized', 'wheels_3'],
  },
  {
    id: 'veh_bicycle',
    symbol: '🚲',
    name: { as: 'চাইকেল', bn: 'সাইকেল', hi: 'साइकिल', en: 'Bicycle' },
    category: 'vehicles',
    subcategory: 'land_vehicles',
    attributes: ['vehicles', 'land', 'manual', 'wheels_2'],
  },
  {
    id: 'veh_truck',
    symbol: '🚚',
    name: { as: 'ট্ৰাক', bn: 'ট্রাক', hi: 'ट्रक (मालवाहक)', en: 'Freight Truck' },
    category: 'vehicles',
    subcategory: 'land_vehicles',
    attributes: ['vehicles', 'land', 'motorized', 'cargo'],
  },
  {
    id: 'veh_scooter',
    symbol: '🛵',
    name: { as: 'স্কুটাৰ', bn: 'স্কুটার', hi: 'स्कूटर', en: 'Motor Scooter' },
    category: 'vehicles',
    subcategory: 'land_vehicles',
    attributes: ['vehicles', 'land', 'motorized', 'wheels_2'],
  },
  {
    id: 'veh_train',
    symbol: '🚂',
    name: { as: 'ৰে\'লগাড়ী', bn: 'রেলগাড়ি', hi: 'रेलगाड़ी', en: 'Railway Train' },
    category: 'vehicles',
    subcategory: 'land_vehicles',
    attributes: ['vehicles', 'land', 'motorized', 'rail'],
  },

  // ─── 13. Water & Air Vehicles (7 Items) ────────────────────────────────────
  {
    id: 'veh_boat',
    symbol: '🛶',
    name: { as: 'নাও / নাওঁ', bn: 'নৌকা', hi: 'नाव (डोंगी)', en: 'Wooden River Boat' },
    category: 'vehicles',
    subcategory: 'water_air_vehicles',
    attributes: ['vehicles', 'water', 'manual_motor'],
  },
  {
    id: 'veh_ferry',
    symbol: '⛴️',
    name: { as: 'ব্ৰহ্মপুত্ৰৰ ফেৰী', bn: 'ফেরি জাহাজ', hi: 'फेरी जहाज', en: 'River Passenger Ferry' },
    category: 'vehicles',
    subcategory: 'water_air_vehicles',
    attributes: ['vehicles', 'water', 'motorized'],
  },
  {
    id: 'veh_plane',
    symbol: '✈️',
    name: { as: 'উৰাজাহাজ', bn: 'উড়োজাহাজ', hi: 'हवाई जहाज', en: 'Airplane' },
    category: 'vehicles',
    subcategory: 'water_air_vehicles',
    attributes: ['vehicles', 'air', 'flying'],
  },
  {
    id: 'veh_helicopter',
    symbol: '🚁',
    name: { as: 'হেলিকপ্তাৰ', bn: 'হেলিকপ্টার', hi: 'हेलिकॉप्टर', en: 'Helicopter' },
    category: 'vehicles',
    subcategory: 'water_air_vehicles',
    attributes: ['vehicles', 'air', 'flying'],
  },
  {
    id: 'veh_ship',
    symbol: '🚢',
    name: { as: 'সাগৰীয় জাহাজ', bn: 'সমুদ্র জাহাজ', hi: 'समुद्री जहाज', en: 'Ocean Ship' },
    category: 'vehicles',
    subcategory: 'water_air_vehicles',
    attributes: ['vehicles', 'water', 'motorized'],
  },
  {
    id: 'veh_sailboat',
    symbol: '⛵',
    name: { as: 'পালতোলা নাও', bn: 'পালতোলা নৌকা', hi: 'पाल वाली नाव', en: 'Sailboat' },
    category: 'vehicles',
    subcategory: 'water_air_vehicles',
    attributes: ['vehicles', 'water', 'wind'],
  },
  {
    id: 'veh_jet',
    symbol: '🛩️',
    name: { as: 'জেট বিমান', bn: 'জেট বিমান', hi: 'जेट विमान', en: 'Jet Aircraft' },
    category: 'vehicles',
    subcategory: 'water_air_vehicles',
    attributes: ['vehicles', 'air', 'flying'],
  },

  // ─── 14. Monsoon & Rainy Weather (7 Items) ─────────────────────────────────
  {
    id: 'wth_rain',
    symbol: '🌧️',
    name: { as: 'বৰষুণ', bn: 'বৃষ্টি', hi: 'बारिश', en: 'Heavy Rain' },
    category: 'weather',
    subcategory: 'rainy_weather',
    attributes: ['weather', 'wet', 'rain', 'monsoon'],
  },
  {
    id: 'wth_thunder',
    symbol: '⛈️',
    name: { as: 'বজ্ৰপাতসহ ধুমুহা', bn: 'বজ্রঝড়', hi: 'गरज के साथ तूफान', en: 'Thunderstorm' },
    category: 'weather',
    subcategory: 'rainy_weather',
    attributes: ['weather', 'wet', 'storm', 'monsoon'],
  },
  {
    id: 'wth_umbrella',
    symbol: '☔',
    name: { as: 'ছাতি আৰু বৰষুণ', bn: 'বৃষ্টির ছাতা', hi: 'बारिश का छाता', en: 'Rain Umbrella' },
    category: 'weather',
    subcategory: 'rainy_weather',
    attributes: ['weather', 'wet', 'protection', 'monsoon'],
  },
  {
    id: 'wth_cloud',
    symbol: '☁️',
    name: { as: 'ডাৱৰীয়া আকাশ', bn: 'মেঘলা আকাশ', hi: 'घने बादल', en: 'Overcast Cloud' },
    category: 'weather',
    subcategory: 'rainy_weather',
    attributes: ['weather', 'cloudy', 'monsoon'],
  },
  {
    id: 'wth_drizzle',
    symbol: '🌦️',
    name: { as: 'পাতলীয়া জিপজিপ বৰষুণ', bn: 'টিপটিপ বৃষ্টি', hi: 'रिमझिम बारिश', en: 'Light Drizzle' },
    category: 'weather',
    subcategory: 'rainy_weather',
    attributes: ['weather', 'wet', 'rain'],
  },
  {
    id: 'wth_lightning',
    symbol: '🌩️',
    name: { as: 'বিজুলী-ঢেৰেকণি', bn: 'বিদ্যুৎ চমক', hi: 'बिजली की चमक', en: 'Lightning Flash' },
    category: 'weather',
    subcategory: 'rainy_weather',
    attributes: ['weather', 'storm', 'monsoon'],
  },
  {
    id: 'wth_droplets',
    symbol: '💧',
    name: { as: 'পানীৰ টোপাল', bn: 'বৃষ্টির ফোঁটা', hi: 'पानी की बूंदें', en: 'Water Droplets' },
    category: 'weather',
    subcategory: 'rainy_weather',
    attributes: ['weather', 'wet'],
  },

  // ─── 15. Bright Sunny Weather (7 Items) ────────────────────────────────────
  {
    id: 'wth_sun',
    symbol: '☀️',
    name: { as: 'উজ্জ্বল ৰ\'দ', bn: 'রোদ ঝলমলে দিন', hi: 'चमकीली धूप', en: 'Bright Sun' },
    category: 'weather',
    subcategory: 'sunny_weather',
    attributes: ['weather', 'dry', 'sun', 'clear'],
  },
  {
    id: 'wth_rainbow',
    symbol: '🌈',
    name: { as: 'ৰামধেনু', bn: 'রংধনু', hi: 'इंद्रधनुष', en: 'Sunny Rainbow' },
    category: 'weather',
    subcategory: 'sunny_weather',
    attributes: ['weather', 'sun', 'sky', 'colorful'],
  },
  {
    id: 'wth_clear',
    symbol: '🌤️',
    name: { as: 'ৰ\'দালি ফৰকাল বতৰ', bn: 'পরিষ্কার মিষ্টি রোদ', hi: 'साफ धूपदार मौसम', en: 'Sun Behind Small Cloud' },
    category: 'weather',
    subcategory: 'sunny_weather',
    attributes: ['weather', 'clear', 'sun'],
  },
  {
    id: 'wth_breeze',
    symbol: '🍃',
    name: { as: 'বসন্তৰ মলয়া বতাহ', bn: 'বসন্তের হাওয়া', hi: 'मंद बयार', en: 'Gentle Spring Breeze' },
    category: 'weather',
    subcategory: 'sunny_weather',
    attributes: ['weather', 'clear', 'wind'],
  },
  {
    id: 'wth_sunrise',
    symbol: '🌅',
    name: { as: 'ৰাতিপুৱাৰ সূৰ্যোদয়', bn: 'ভোরের সূর্যোদয়', hi: 'प्रातः सूर्योदय', en: 'Morning Sunrise' },
    category: 'weather',
    subcategory: 'sunny_weather',
    attributes: ['weather', 'sun', 'clear'],
  },
  {
    id: 'wth_sunglasses',
    symbol: '🕶️',
    name: { as: 'ৰ\'দ চশমা', bn: 'রোদচশমা', hi: 'धूप का चश्मा', en: 'Sunny Shades' },
    category: 'weather',
    subcategory: 'sunny_weather',
    attributes: ['weather', 'sun', 'protection'],
  },
  {
    id: 'wth_sparkles',
    symbol: '✨',
    name: { as: 'জিলমিল পোহৰ', bn: 'ঝলমলে আলো', hi: 'चमकती किरणें', en: 'Sunny Radiance' },
    category: 'weather',
    subcategory: 'sunny_weather',
    attributes: ['weather', 'clear'],
  },
];
